config/routes.rb
ADSUM2::Application.routes.draw do
  get "courses/take_attendance"
  get "courses/points"
  get "courses/statistic"

  resources :lecture_days

  resources :pass_q_points

  resources :pass_d_points

  resources :enrollments

  resources :attendances

  resources :designated_points

  resources :quick_points

  resources :students do
    collection { post :import }
  end

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :courses

  resources :users
  
  get "sessions/new"

  resources :courses do
    get "take_attendance", :on => :member
    get "points", :on => :member
    get "statistic", :on => :member
  end
  
   resources :students do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'dp', on: :member
  end

  root to: 'sessions#new'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
   skip_before_filter :verify_authenticity_token
  # GET /courses
  # GET /courses.json
  def index
    @current_user = User.find_by_id(session[:user_id])
    @courses = @current_user.courses.paginate page: params[:page], order: 'created_at asc', per_page: 25
    if @current_user.courses.empty?
      redirect_to new_course_url, notice: "You Have No Courses Yet"
      return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @current_user = User.find_by_id(session[:user_id])
    session[:course_id] = @course.id
    if @course.students.count.zero?
      redirect_to new_student_path, notice: "Add Students!"
    else
    @pass_d_point = @course.pass_d_points.build
    @designated_point = DesignatedPoint.find_by_id(session[:d_id])
    @students = @course.students.paginate page: params[:page], order: 'lname asc', per_page: 25

    if @course.user_id == @current_user.id
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @students }
    end
    else
      redirect_to login_url, notice: "Not Authorized"
    end
    end
  end
  # GET /courses/new
  # GET /courses/new.json
  def new
    @user = User.find_by_id(session[:id])
    @course = Course.new
    @lecture_day = @course.lecture_days.build
    @designated_points = @course.designated_points.build
 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    @current_user = User.find_by_id(session[:user_id])
    session[:course_id] = @course.id

    if @course.user_id == @current_user.id
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
    else
      redirect_to login_url, notice: "Not Authorized"
    end
  end

  # POST /courses
  # POST /courses.json
  def create
     if (params[:course])
        @course = Course.new(params[:course])
        @user = User.find_by_id(session[:user_id])
     else
        params[:course] = {:name=>params[:title], 
                            :f_day=>params[:description],   
                            :l_day=>params[:price]
                            }
        @course = Course.new(params[:course])
        @course.user_id = session[:user_id]
    end
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: courses_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])
    
    if (!params[:course])
     params[:course] = {:name=>params[:title], 
                            :f_day=>params[:description],   
                            :l_day=>params[:price]
                            }   
    end

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
  def take_attendance
    @course = Course.find(params[:id])
    @students = @course.students.paginate page: params[:page], order: 'lname asc', per_page: 25
    @attendance = @course.attendances.build 
    @course = Course.find(params[:id])
    @current_user = User.find_by_id(session[:user_id])


    if @course.user_id == @current_user.id
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
    else
      redirect_to login_url, notice: "Not Authorized"
    end
  end
  
  def statistic
    @course = Course.includes(students: :attendances).find(params[:id])
    @current_user = User.find_by_id(session[:user_id])
    @students = @course.students.paginate page: params[:page], order: 'lname asc', per_page: 25


    if @course.user_id == @current_user.id
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
    else
      redirect_to login_url, notice: "Not Authorized"
    end
  end
  
  def points
    @course = Course.find(params[:id])
    @pass_q_point = @course.pass_q_points.build 
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= nested_form_for @course, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label "Course Name:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "First Day:", :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :f_day, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Last Day:", :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :l_day, :class => 'date_select' %>
    </div>
  </div>
  <p>
  <div class="control-group">
  	<%= f.label "Lecture Days", :class => 'control-label' %>
  	<div class="controls">
  	<%= f.fields_for 'lecture_days' do |ff| %>
		M<%= ff.check_box :monday %>
		T<%= ff.check_box :tuesday %>
		W<%= ff.check_box :wednesday %>
		R<%= ff.check_box :thursday %>
		F<%= ff.check_box :friday %>
		Sa<%= ff.check_box :saturday %>
		Su<%= ff.check_box :sunday %>
	<% end %><br />
	</div>
  </div>
  </p>
  
  
  		<%= f.fields_for 'designated_points' do |f4| %>
  		<p>
		  <div class="control-group">
		    <%= f4.label "Point Description", :class => 'control-label' %>
		    <div class="controls">
		    <%= f4.text_field :name %>
		    </div>
		  </div>
		  <div class="control-group">
		    <%= f4.label "Amount of Points", :class => 'control-label' %>
		    <div class="controls">
		    <%= f4.number_field :num %>
		    </div>
		  </div>
		  <div class="field">
			<%= f4.hidden_field :course_id, :value => @course.id %>
		  </div>
		  <div class="field">
		  <%= f4.link_to_remove "Remove Designated Point", :class => 'link'%>
		  </div>
  		<% end %>
  		</p>
<p></p><p>
<%= f.link_to_add "Add Another Designated Point", :designated_points, :class => 'btn'%>
</p>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                courses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1>Edit Info for <%= @course.name %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1>All Courses for <%= @current_user.name %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name("First Day") %></th>
      <th><%= model_class.human_attribute_name("Last Day") %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course, :class => 'link' %></td>
        <td><%= course.f_day %></td>
        <td><%= course.l_day %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_course_path(course), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      course_path(course),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @courses %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_course_path,
            :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1>Create a New Course</h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%= @course.name %></h1>
</div>

<dl class="dl-horizontal">
<table class="table table-striped">
  <thead>
  <tr>
  	<th>|Points|</th>
  	<th>|Preferred|</th>
  	<th>|First|</th>
  	<th>|Last|</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
	<tbody>
<% @students.each do |student| %>
  <tr class="List" onmouseover="this.className='hover'" onmouseout="this.className='List'">
  	<td> <strong><%= student.points %></strong></td>
  	<td><%= link_to student.preferred_name, student %></td>
    <td><%= link_to student.fname, student %></td>
    <td><%= student.lname %></td>
    <td><%= link_to image_tag("up.png"), increase_student_path(student), :method => :put , remote: false%></td>
    <td><%= link_to image_tag("down.png"), decrease_student_path(student), :method => :put, remote: false %></td>
	<td><%= render "/pass_d_points/form", :student => student %></td>
  </tr>
<% end %>
</tbody>
</table>
</dl>

<div class="form-actions">
  <%= link_to t('.back'),
              courses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn' %>
  <%= link_to t('Take Attendance'),
 			  take_attendance_course_path(@course.id), :class => 'btn' %>	
  <%= link_to t('Add Students'),
              new_student_path, :class => 'btn' %>
  <%= link_to t('Statistics'),
 			  statistic_course_path(@course.id), :class => 'btn' %>
</div>


<%= will_paginate @students %>

app/views/courses/statistic.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1>Stats for <%= @course.name %></h1>
</div>

<dl class="dl-horizontal">
<table class="table table-striped">
	<thead>
  <tr>
  	<th>|Preferred|</th>
    <th>|First|</th>
    <th>|Last|</th>
    <th>|Points|</th>
    <th>|Present|</th>
    <th>|Tardy|</th>
    <th>|Absent|</th>
    <th>|Excused|</th>
  </tr>
  </thead>
  <tbody>

<% @students.each do |student| %>
  <tr class="List" onmouseover="this.className='hover'" onmouseout="this.className='List'">
  	<td><%= link_to student.preferred_name, student %></td>
    <td><%= link_to student.fname, student %></td>
    <td><%= link_to student.lname, student %></td>
	<td><%= student.points %></td>
	<td><%= student.attendances.count(:conditions => { :present => true}) %></td>
	<td><%= student.attendances.count(:conditions => { :tardy => true}) %></td>
	<td><%= student.attendances.count(:conditions => { :absent => true}) %></td>
	<td><%= student.attendances.count(:conditions => { :excused => true}) %></td>
  </tr>
<% end %>
</tbody>
</table>
</dl>

<div class="form-actions">
  <%= link_to t('.back'),
              @course, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn' %>
  <%= link_to t('Add Students'),
              new_student_path, :class => 'btn' %>
  <%= link_to t('Take Attendance'),
 			  take_attendance_course_path(@course.id), :class => 'btn' %>
</div>


<%= will_paginate @students %>

app/views/courses/take_attendance.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1>Attendance for <%= @course.name %></h1>
</div>

<dl class="dl-horizontal">
<table class="table table-striped">
	<thead>
  <tr>
  	<th>|Preferred|</th>
  	<th>|First|</th>
  	<th>|Last|</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @students.each do |student| %>
  <tr class="List" onmouseover="this.className='hover'" onmouseout="this.className='List'">
  	<td><%= link_to student.preferred_name, student %></td>
    <td><%= link_to student.fname, student %></td>
    <td><%= student.lname %></td>
	<%= render '/attendances/form', :f => student,:course_id => @course.id, :student_id => student.id %>
  </tr>
<% end %>
</tbody>
</table>
</dl>

<div class="form-actions">
  <%= link_to t('.back'),
              @course, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn' %>
  <%= link_to t('Take Attendance'),
 			  take_attendance_course_path(@course.id), :class => 'btn' %>	
  <%= link_to t('Old Attendances'),
              attendances_path, :class => 'btn' %>
  <%= link_to t('Statistics'),
 			  statistic_course_path(@course.id), :class => 'btn' %>
</div>


<%= will_paginate @students %>