config/routes.rb
ADSUM2::Application.routes.draw do
  get "courses/take_attendance"
  get "courses/points"
  get "courses/statistic"

  resources :lecture_days

  resources :pass_q_points

  resources :pass_d_points

  resources :enrollments

  resources :attendances

  resources :designated_points

  resources :quick_points

  resources :students do
    collection { post :import }
  end

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :courses

  resources :users
  
  get "sessions/new"

  resources :courses do
    get "take_attendance", :on => :member
    get "points", :on => :member
    get "statistic", :on => :member
  end
  
   resources :students do
    put 'decrease', on: :member
    put 'increase', on: :member
    put 'dp', on: :member
  end

  root to: 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ADSUM" %></title>
  	<%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">ADSUM</a>
          <div class="container nav-collapse">
            <ul class="nav">
            <% if session[:user_id] %>
            <li><%= link_to "View Courses", courses_path %></li>
	    	<li><%= link_to "Edit Account", edit_user_path(session[:user_id]) %></li>
	        <li><%= link_to "Logout", logout_path, method: :delete %></li>	     	
	     	<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Menu</h3>
              <ul class="nav nav-list">
                <% if session[:user_id] %>
                <li class="nav-header">Choose a Course</li>
                <% @courses.each do |course| %>
                <li><%= link_to course.name, course  %></li>
                <% end %>
                <li><%= link_to "Add Course", new_course_path  %></li>
                <% else %>
               	<li class="nav-header">Welcome!</li>
                <li><%= link_to 'Login to View Options', login_path %></li>
                <% end %>

              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; VSU Spring 2013 Senior Seminar</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults, "nested_form"%>

  </body>
</html>